# Generated by Django 5.1.2 on 2024-10-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantMapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('specialty', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=255)),
                ('learning_form', models.CharField(max_length=255)),
                ('total_students', models.IntegerField(blank=True, default=0, null=True)),
                ('budget_rf', models.IntegerField(blank=True, default=0, null=True)),
                ('budget_local', models.IntegerField(blank=True, default=0, null=True)),
                ('paid_students', models.IntegerField(blank=True, default=0, null=True)),
                ('average_score', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
