# Generated by Django 5.0.14 on 2025-12-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantrecord',
            options={'ordering': ['-year', 'specialty']},
        ),
        migrations.AddField(
            model_name='applicantrecord',
            name='year',
            field=models.IntegerField(blank=True, default=2024, help_text='Год поступления', null=True),
        ),
    ]
