# Generated by Django 5.0.14 on 2026-01-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_alter_applicantrecord_options_applicantrecord_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('math_score', models.FloatField()),
                ('russian_score', models.FloatField()),
                ('profile_score', models.FloatField()),
                ('avg_score', models.FloatField()),
                ('specialty_code', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('learning_form', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=255)),
                ('passing_score', models.FloatField()),
            ],
            options={
                'ordering': ['specialty', 'fio'],
            },
        ),
    ]
