# Generated by Django 5.0.14 on 2026-01-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0003_studentrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantrecord',
            name='budget_local',
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='profile_subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
