# Generated by Django 5.0.14 on 2026-01-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0004_update_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='year',
            field=models.IntegerField(blank=True, help_text='Год поступления', null=True),
        ),
    ]
